language: scala

scala:
  - 2.12.6
  - 2.11.7
  - 2.10.6

jdk:
  - openjdk8
  - openjdk7

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport coveralls

addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: short-hostname

# Use new faster, container-based builds
sudo: false
